Features
carlos-ssh/ContactForm pull request #1
Opened 2021-06-29 16:39 UTC by carlos-ssh

This PR contains these changes:
 

1. Name field accepts up to 30 chars.
2. Email field accepts only emails.
3. Message field accepts up to 500 chars.
4. All fields have placeholder text.
5. All fields have the correct type.
6. A user cannot submit the form if one or more of the fields is empty.
7. Collect data by using the Formspree service.

2021-06-30 23:37 UTC, voscarmv requested changes
Hi @carlos-ssh , 

Good job so far!

- Your repository shows no linter errors.
- Your README file is acceptable but can be improved.
- Your commit messages are detailed and useful.
- Your Pull Request description is also good.
- Your GitHub flow is also correct.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- Your form contains a few errors as well regarding the input field naming and the use of incorrect tags. Note the code comments below for more.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- There are some best HTML/CSS practices that can be applied to your code. Please read the comments for more info on these!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-30 23:37 UTC, voscarmv commented on index.html
> +        >
- [ ] Please mind the indentation of this `form` tag, in order to keep with the best HTML practices.

2021-06-30 23:37 UTC, voscarmv commented on index.html
> +            <input type="text" class="txt-form" name="fname" placeholder="Enter text here" required maxlength="500"><br>
- [ ] We have two input fields with the same name `fname` here. Please assign a different name to the last input field, which is supposed to contain the message instead of the first name.
- [ ] The last input field is supposed to be a `textarea`. Please change it.

2021-06-30 23:37 UTC, voscarmv commented on index.html
> +      </div> -->
- [ ] **[OPTIONAL]** Instead of just leaving commented code in your files, it's a better practice to just delete it. Please fix this.

2021-06-30 23:37 UTC, voscarmv commented on css/main.css
> +} */
- [ ] **[OPTIONAL]** Please remove the commented code in your CSS files. If it's not being used, it's better practice to simply delete it.

2021-07-02 18:27 UTC, KabohaJeanMark approved these changes
## _Status:_ Approved  :hamster: :rocket:
Hi @carlos-ssh, 

Your project is complete!  Thank you for the amazing job of making all the requested changes given by the first previous reviewer. You paid good attention to detail 💪🏾 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You should strongly consider:
- [ ] It is highly recommended that in the future you always follow the git-flow guidelines and make a pull request from the feature branch with a descriptive name to the main branch. For example a Pull Request from the ft-contact-form branch to the main branch. 

Good luck in your future projects and happy coding :relaxed:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-03 01:47 UTC, merged